services:
  postgres-comments:
    image: postgres:alpine
    ports:
      - "5454:5432"
    container_name: "finance_postgres"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
volumes:
  postgresql:
