@HOST = http://localhost:8080

POST {{HOST}}/users
Content-Type: application/json
Cookie: ""

{
  "lastName": "José Victor",
  "firstName": "Araújo",
  "username": "não deve estar em branco",
  "email": "user@gmail.com",
  "password": "123456"
}

###
POST {{HOST}}/auth
Content-Type: application/json

{
  "email": "user3@gmail.com",
  "password": "123456"
}

###
POST {{HOST}}/workspaces HTTP/1.1
Content-Type: application/json

{     
	"name": "aquiss",
    "icon": "MONEY"
}

###
GET {{HOST}}/workspaces HTTP/1.1

###
POST {{HOST}}/auth/clear-cookies HTTP/1.1

###
POST {{HOST}}/transactions/income HTTP/1.1
Content-Type: application/json

{
  "name": "teste",
  "amount": 45,
  "payment_method": "PIX",
  "workspaceId": "iw1JKFjuA0"
}

###
POST {{HOST}}/transactions/expense HTTP/1.1
Content-Type: application/json

{
  "name": "Amburguer",
  "amount": 4,
  "payment_method": "PIX",
  "workspaceId": "iw1JKFjuA0",
  "status": "PENDING"
}

###
GET {{HOST}}/transactions/iw1JKFjuA0 HTTP/1.1